const shoeData = [
    {
        id: 1,
        brandSrc: "/sneaker_images/brands/nike-dunk-low-fog-grey.png",
        shoeBrand: "Nike",
        shoeDetail: "Nike Airforce One Retro Grey & White 2022",
        arrivalSrc: "/sneaker_images/adidas-black.jpg",
        topLeftPrice: "# " + 150 + ".00",
        shoeDescription: "Adidas Rough Dark Blue",
    },
    {
        id: 2,
        brandSrc : "/sneaker_images/brands/converse-chunk-white.png",
        shoeBrand: "Converse",
        shoeDetail: "All Star Converse Beige with Heart Eyes Custom 2023",
        arrivalSrc: "/sneaker_images/adidas-grey.jpg",
        topLeftPrice: "# " + 90.00 + ".00",
        shoeDescription: "Adidas Military Runner Grey",
    },
    {
        id: 3,
        brandSrc: "/sneaker_images/brands/vans-old-skool-black.png",
        shoeBrand: "Vans",
        shoeDetail: "Vans off the Wall Black and White 2022",
        arrivalSrc: "/sneaker_images/adidas-red.jpg",
        topLeftPrice: "#" + 100.00 + ".00",
        shoeDescription: "Adidas Hu Red",
    },
    {
        id: 4,
        brandSrc : "/sneaker_images/brands/converse-chunk-white.png",
        shoeBrand: "Converse",
        shoeDetail: "All Star Converse Beige with Heart Eyes Custom 2023",
        arrivalSrc: "/sneaker_images/adidas-grey.jpg",
        topLeftPrice: "#" + 90.00 + ".00",
        shoeDescription: "Adidas Military Runner Grey",
    },
    {
        id: 5,
        brandSrc: "/sneaker_images/brands/vans-old-skool-black.png",
        shoeBrand: "Vans",
        shoeDetail: "Vans off the Wall Black and White 2022",
        arrivalSrc: "/sneaker_images/adidas-black.jpg",
        topLeftPrice: "#" + 100.00 + ".00",
        shoeDescription: "Adidas Rough Dark Blue",
    },
    {
        id: 6,
        brandSrc: "/sneaker_images/brands/nike-dunk-low-fog-grey.png",
        shoeBrand: "Nike",
        shoeDetail: "Nike Airforce One Retro Grey & White 2022",
        arrivalSrc: "/sneaker_images/adidas-red.jpg",
        topLeftPrice: "#" + 150.00 + ".00",
        shoeDescription: "Adidas Hu Red",
    },
    {
        id: 7,
        brandSrc : "/sneaker_images/brands/converse-chunk-white.png",
        shoeBrand: "Converse",
        shoeDetail: "All Star Converse Beige with Heart Eyes Custom 2023",
        arrivalSrc: "/sneaker_images/adidas-grey.jpg",
        topLeftPrice: "#" + 90.00 + ".00",
        shoeDescription: "Adidas Military Runner Grey",
    },
    {
        id: 8,
        brandSrc: "/sneaker_images/brands/nike-dunk-low-fog-grey.png",
        shoeBrand: "Nike",
        shoeDetail: "Nike Airforce One Retro Grey & White 2022",
        arrivalSrc: "/sneaker_images/adidas-black.jpg",
        topLeftPrice: "#" + 150.00 + ".00",
        shoeDescription: "Adidas Rough Dark Blue",
    },
    {
        id: 9,
        brandSrc: "/sneaker_images/brands/vans-old-skool-black.png",
        shoeBrand: "Vans",
        shoeDetail: "Vans off the Wall Black and White 2022",
        arrivalSrc: "/sneaker_images/adidas-red.jpg",
        topLeftPrice: "#" + 100.00 + ".00",
        shoeDescription: "Adidas Hu Red",
    },
    
]

export default shoeData;